jam-embedded article update
telerik/fiddler-jam-docs pull request #69
Opened 2022-06-28 13:24 UTC by NickIliev

https://kinvey.atlassian.net/browse/FJ-937

and 

https://kinvey.atlassian.net/browse/FJ-936

2022-07-05 15:08 UTC, rosen-vladimirov commented on portal/jam-embedded-api.md
> +The following code snippets demonstrate a basic Fiddler Jam Embedded implementation you can use as a reference and run through a test localhost server.
This sounds like the implementation cannot be used for production server

2022-07-05 15:10 UTC, rosen-vladimirov commented on portal/jam-embedded-api.md
>  1. Obtain and store your unique Fiddler Jam Embedded API key.
we need to explain how

2022-07-05 15:14 UTC, rosen-vladimirov commented on portal/jam-embedded-api.md
> +                        <label>With <b>captureDom = false</b>, and <b>captureVideo = true</b>, you can start capturing with pixel-percet video recording (captures iframes), but also requires an explc
explcit -> explicit

2022-07-05 15:22 UTC, rosen-vladimirov commented on portal/jam-embedded-api.md
> +        document.getElementById('jam-share-url').innerHTML = 'Share URL: ' +  '<a href="' + jamShareUrl + '">'+ jamShareUrl +'</a>';
add ` target="_blank"`, so the link will not be opened in the same tab

2022-07-05 15:23 UTC, rosen-vladimirov commented on portal/jam-embedded-api.md
> +1. You can **record a DOM video** while setting  `captureDom: true` and `captureVideo: true`. The DOM video recording is not pixel-perfect, and won't contain recordings from iframes. This method for
Isn't this the default method if you do not pass any configuration?

2022-07-14 06:21 UTC, rosen-vladimirov requested changes
I do not see any information about the video masking settings

2022-07-14 06:21 UTC, rosen-vladimirov commented on portal/jam-embedded-api.md
> +                <script src="https://downloads.getfiddler.com/jam-embedded/fiddler-jam-embedded.js" id="jamEmbeddedScript" async></script>
you can set crossorigin="anonymous" directly here inside the script tag.

2022-07-14 06:21 UTC, rosen-vladimirov commented on portal/jam-embedded-api.md
> +                    jamEmbeddedScript.crossOrigin = 'anonymous';  // set crossOrigin to enable CORS (and to be able to use the load event below)
The correct name of the attribute is crossorigin: https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/crossorigin

2022-07-14 06:21 UTC, rosen-vladimirov commented on portal/jam-embedded-api.md
> +self.importScripts(`https://downloads.getfiddler.com/jam-embedded/fje-service-worker.js`);
The format on the test docs site does not look good when ` are used, maybe you can use `"` here
![Screen Shot 2022-07-14 at 9 09 51](https://user-images.githubusercontent.com/8351653/178912275-f1a0114f-2771-4d51-9736-a2fd1bb4c521.png)

2022-07-14 06:21 UTC, rosen-vladimirov commented on portal/jam-embedded-api.md
> +Í
strange symbol here

2022-07-14 06:21 UTC, rosen-vladimirov commented on portal/jam-embedded-api.md
> +                // Adding the custom implmenetaion
implmenetaion -> implementation

2022-07-14 06:21 UTC, rosen-vladimirov commented on portal/jam-embedded-api.md
> +        <script src="https://downloads.getfiddler.com/jam-embedded/fiddler-jam-embedded.js" id="jamEmbeddedScript" async></script>
set crossorigin="anonymous" directly here

2022-07-14 06:21 UTC, rosen-vladimirov commented on portal/jam-embedded-api.md
> +                // Adding the custom implmenetaion
Also, we can add a comment that they can place the Jam Embedded implementation here as well, but we recommend them to use a separate file for easier maintenance

2022-07-14 06:21 UTC, rosen-vladimirov commented on portal/jam-embedded-api.md
> +// Use this method when explicit permissoin is required to start video recording (for example, the uswer denied permission after calling start())
the uswer -> the user

2022-07-15 08:53 UTC, rosen-vladimirov commented on portal/jam-embedded-api.md
> +## Limitations and Log Specifics
Can you please add information that masking is not supported for screenshots and also that there's a performance issue when capturing screenshots for large applications.

2022-07-20 05:25 UTC, rosen-vladimirov commented on .gitignore
> +_tempconfig.\`yml
Is this change intentional?

2022-07-20 05:25 UTC, rosen-vladimirov approved these changes

2022-07-20 07:09 UTC, NickIliev commented on .gitignore
> +_tempconfig.\`yml
actually no :) good catch!

2022-07-20 07:29 UTC, merged